# Generated by Django 4.1.2 on 2022-11-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersareainfo',
            name='area_coordinates',
            field=models.FileField(blank=True, max_length=254, upload_to='area_info/documents_coordinates/%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='usersareainfo',
            name='google_earth',
            field=models.FileField(blank=True, max_length=254, upload_to='area_info/documents_ge/%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='usersareainfo',
            name='map',
            field=models.FileField(blank=True, max_length=254, upload_to='area_info/documents_map/%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='usersareainfo',
            name='sketch_plan',
            field=models.FileField(blank=True, max_length=254, upload_to='area_info/documents_sp/%Y%m%d'),
        ),
    ]
