# Generated by Django 4.1.2 on 2022-11-25 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_usersareainfo_area_coordinates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='assigned_id',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='nationality',
            field=models.CharField(max_length=50),
        ),
    ]
